### ISSUE TITLE
keep menu open after selecting menu item -- multi-select

### ISSUE THREAD

**Issue by srevenant** [StreakYC/react-menu-list#20]
I'd like to keep the menu open after an item is chosen, so I can build a multi-select menu.  I can't tell if this is supported or not.  Is there a way to configure it to allow this?

Thanks!

**Comment by Macil** [comment]
Yes, you can do this by calling the `stopPropagation()` method on the event object in the MenuItem's onItemChosen callback. Calling that stops the event from propagating to the MenuButton which would act on it by closing the menu.
