### ISSUE TITLE
Is there a way to stopPropagation MenuItem's onItemChosen?

### ISSUE THREAD

**Issue by wegry** [StreakYC/react-menu-list#39]
With react-menu-list@6.1.2 and react@17.0.2, it seems like `MenuItem`'s `onItemChosen`'s event parameter honor a `e.stopPropagation()` call like I'd expect.

Here's an example https://codesandbox.io/s/cranky-rui-g31gq7?file=/src/App.tsx

**Comment by Macil** [comment]
The stopPropagation() called on the ItemChosenEvent only applies to it and not the click event that caused the ItemChosenEvent. You should attach an `onClick` handler to a parent of the MenuItem component and call stopPropagation() on click events as they bubble up to accomplish what you want. (I considered whether ItemChosenEvent.stopPropagation() should stopPropagate its source event too, but I think they're separate concerns. I'm not sure they should always be bundled together.)

**Comment by wegry** [comment]
Sounds like it's working as designed. Thanks!
