### ISSUE TITLE
Allow customisation of div elements used as anchor inside SubMenuItem

### ISSUE THREAD

**Issue by hamishtaplin** [StreakYC/react-menu-list#6]
E.g. [this one](https://github.com/StreakYC/react-menu-list/blob/master/src/SubMenuItem.js#L276). Not being able to (at least) provide a class (a component would be better) results in having to write (not ideal) `> div` selectors to target this element in CSS. The main issue being that the submenu aligns to this elements and so any `margin` or `padding` on the parent causes the submenu to overlap.

**Comment by hamishtaplin** [comment]
Thanks for getting back to me, really liking this lib so far.

This inconsistency with styling `MenuItem` and `SubMenuItem` is exactly what I ran into. Your solution sounds good though, happy to test it out for you.

**Comment by AgentME** [comment]
SubMenuItem no longer has the inner wrapper div in version 5.0.0. Let me know if you have any issues with it. (There's a new changelog now too!)
