### ISSUE TITLE
Customize dropdown container

### ISSUE THREAD

**Issue by SergeyShablenko** [StreakYC/react-menu-list#7]
It is not possible to add any styles or classes to the very first wrapper of dropdown menu. I`m having an issue, when I need to change menu zIndex, because it is hidden by page contents

**Comment by SergeyShablenko** [comment]
`Dropdown` or `MenuList` whatever it is, the first div with absolute coordinates for menu

**Comment by Macil** [comment]
The Dropdown component is meant to be used with SubMenuItem or MenuButton (which both use [react-float-anchor](https://github.com/StreakYC/react-float-anchor#readme) to create a floating element with a z-index property for the Dropdown to be rendered into). Dropdown isn't meant to be used on its own.

**Comment by SergeyShablenko** [comment]
The following screenshot shows div which I need to customize

![selection_118](https://user-images.githubusercontent.com/13334277/46069592-8a018780-c184-11e8-9fa0-2954d3b85984.png)

I\`m rendering menu this way, and it works
On which component should I add your prop?

```jsx
renderMenu(menu) {
    return <Dropdown>
      <MenuList>
        {
          menu.map(item => item.children ? this.renderSubmenu(item) : this.renderMenuItem(item))
        }
      </MenuList>
    </Dropdown>;
  }

  renderSubmenu(submenu) {
    return <SubMenuItem key={submenu.id}>
      // children
    </SubMenuItem>;
  }

  renderMenuItem(item) {
    return <MenuItem key={item.id}>
      // children
    </MenuItem>;
  }

```

**Comment by Macil** [comment]
What component is that element?

Only MenuButton and SubMenuItem contain an element with position:fixed if I remember right, so if that element is a react-menu-list component, I assume it's one of those. You can use the `menuZIndex` prop on those.

**Comment by Macil** [comment]
I'm closing the issue because I don't believe there's a problem with react-menu-list here. Feel free to reply if you still need help.
